### ISSUE TITLE
Is language a problem?

### ISSUE THREAD

**Issue by Cletip** [vascoferreira25/org-mode-incremental-reading#14]
Hello,

I think that everything was done correctly at home: installation, copy and paste of the example, creation of the deck "Test" to try. Unfortunately, the message "Updated card" does not help me, because the deck does not contain any card.

And then I thought that in anki-editor, the language of anki had its influence. Is it the same here?

Thanks in advance

PS : I tried with my language and the english language, and the creation of map to anki still does not work

**Comment by vascoferreira25** [comment]
Hi!

I've fixed the incorrect version and tags field types and it should work now. I still have to improve error handling, sorry about that.

**Comment by Cletip** [comment]
Thank you for your responsiveness and your answer.

I'm sorry, but it still doesn't seem to work. I did the following: 
- copy and paste your example
- open anki
- create the "Test" package
- call the "incremental-reading-parse-cards" command

I get the following message "Updated card."
But, my "Test" package is still empty, which I don't understand.
And I repeat (just to make it clear): I have anki in a language other than English (French)

Did I miss a step?

**Comment by vascoferreira25** [comment]
Did you install the anki plugin - anki-connect? I don't think it is a problem with the language.

**Comment by Cletip** [comment]
Yes I installed it, anki-editor works perfectly.

**Comment by vascoferreira25** [comment]
I believe that the example you copied already had an ID right? As that card doesn't exist in Anki it won't update. Please try to parse this card instead (notice that it doesn't have an ID):

```
#+ATTR_DECK: Test
#+ATTR_TYPE: Cloze
#+ATTR_TAGS: incremental-reading emacs
#+BEGIN_ANKI org
#+ATTR_FIELD: Text
#+BEGIN_FIELD
{{c1::Return Over Investment or ~ROI~::Formula}} is a measure of how well the
investment of a company is going.
#+END_FIELD
#+END_ANKI
```

**Comment by vascoferreira25** [comment]
I've also tried with a french text and it works. Just notice that new cards don't have an ATTR_ID. If the card was not added to anki, remove the ID (in case it has one) and try to parse again.

The card I tried:
```
#+ATTR_DECK: Test
#+ATTR_TYPE: Cloze
#+ATTR_TAGS: incremental-reading emacs
#+BEGIN_ANKI org
#+ATTR_FIELD: Text
#+BEGIN_FIELD
Je m’appelle Jessica. Je suis une fille, je suis française et j’ai treize
ans. Je vais à l’école à Nice, mais j’habite à Cagnes-Sur-Mer. J’ai deux
frères. Le premier s’appelle Thomas, il a quatorze ans. Le second s’appelle
Yann et il a neuf ans. Mon papa est italien et il est fleuriste. Ma mère est
allemande et est avocate. Mes frères et moi parlons français, italien et
allemand à la maison. Nous avons une grande maison avec un chien, un poisson et
deux chats.

Aujourd’hui, on est samedi, nous rendons visite à notre grand-mère. Elle a 84
ans et elle habite à Antibes. J’adore ma grand-mère, elle est très
gentille. Elle fait des bons gâteaux.

Lundi, je retourne à l’école. Je suis contente, je vais voir Amélie. C’est ma
{{c1::meilleure amie}}. J’aime beaucoup l’école. Mes matières préférées sont le
français et le sport. J’aime beaucoup lire et je nage très bien.
#+END_FIELD
#+END_ANKI
```

**Comment by vascoferreira25** [comment]
Also, use the updated version of the package. I updated the package yesterday.

**Comment by Cletip** [comment]
Just a little clarification first: we agree that if the map does not exist, then it will be created?

Okay then:

- I have activated the incremental-reading-mode and the anki-editor-mode (oops)
- I copied and pasted your example
- I call "incremental-reading-parse-cards"

A "nil" identifier is assigned, same message "Updated card".
But still no new card.

Well, when I said in French, I didn't mean the text. But the options to put. 
Example with anki-editor (take attention to the type): 
```

** Item
:PROPERTIES:
:ANKI_NOTE_TYPE: General (two ways)
:END:

*** Recto
the front
*** Verso
the back
```

**Comment by vascoferreira25** [comment]
If a "nil" appeared in the id attribute, it means that an error occurred when creating a card in Anki. Before attempting to parse the cards, remove the id attribute and then try again.

Does the example you wrote work with anki-editor-mode? The name of the headings (Recto and Verso) should be the names of the fields of the cards in Anki, like this:

![20221104_101312_520_anki_Lsvc5T6VKC](https://user-images.githubusercontent.com/9872065/199948435-f4d32efd-f50a-40bd-8d03-b7cbda1265b3.png)

Following your example, the card template with incremental-reading mode should be (make sure to change the deck name to your deck):

```
#+ATTR_DECK: Test
#+ATTR_TYPE: General (two ways)
#+ATTR_TAGS: incremental-reading emacs
#+BEGIN_ANKI org
#+ATTR_FIELD: Recto
#+BEGIN_FIELD
Recto text
#+END_FIELD

#+ATTR_FIELD: Verso
#+BEGIN_FIELD
Verso text
#+END_FIELD
#+END_ANKI
```

**Comment by Cletip** [comment]
Damn, I unintentionally translated the line with "anki_note_type", 
correction:
`#+ATTR_TYPE: Généralités (deux sens)`
(I'll take it into account of course)

Yes, this example works with anki-editor.

Thank you for the precision of the "nil", it helped me to understand where the problem came from.

So I tried again with this : 

```
#+ATTR_DECK: Test
#+ATTR_TYPE: Généralités (deux sens)
#+ATTR_TAGS: incremental-reading emacs
#+BEGIN_ANKI org
#+ATTR_FIELD: Recto
#+BEGIN_FIELD
Recto text yes
#+END_FIELD

#+ATTR_FIELD: Verso
#+BEGIN_FIELD
Verso text
#+END_FIELD
#+END_ANKI

```

I activated both modes, called the "incremental-reading-parse-cards" function, and everything works perfectly!

**Comment by vascoferreira25** [comment]
I'm glad. I hope this package helps you 😄.

**Comment by Cletip** [comment]
I wanted to edit my message, but you were too quick x)

Thanks a lot for your help! 
I think it was the language (Front becomes "Recto", Back "Verso" etc). Maybe you could warn the users about the changes to be made in the readme?

Thanks again for your help :)
